name: Build Android APK

on:
  push:
    branches:
      - main
  workflow_dispatch: # يسمح لك بتشغيل البناء يدوياً من زر Actions

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # 1. استدعاء الكود
      - name: Checkout Code
        uses: actions/checkout@v3

      # 2. إعداد جافا 17 (ضروري لـ Gradle الحديث)
      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      # 3. إعداد بايثون
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 4. تثبيت المكتبات وأداة Flet
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flet
          pip install -r requirements.txt

      # 5. بناء ملف APK
      # الأمر 'yes' سيقوم بالضغط على y تلقائياً عند طلب تثبيت Flutter
      # --verbose يعطينا تفاصيل عشان لو حصل حاجة نعرف السبب
      - name: Build APK
        run: |
          yes | flet build apk --verbose

      # 6. رفع الملف النهائي
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: IPTV-Terminator-App
          path: build/apk/app-release.apk
